# Generated by Django 6.1 on 2026-08-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headquarter", "0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/headquarter/%Y/%m/%d"),
        ),
    ]
