# Generated by Django 6.1 on 2026-08-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headquarter", "0005_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/headquarter/%Y/%m/%d"
            ),
        ),
    ]
